import type { MetadataRoute } from "next";
import { site } from "@/lib/site";

const routes = [
  "",
  "/platform",
  "/platform/see-it-work",
  "/platform/framework-intelligence",
  "/platform/gap-analysis",
  "/platform/remediation",
  "/platform/knowledge-transformation",
  "/platform/verification-trust",
  "/platform/knowledge-governance",
  "/platform/standards-accreditation",
  "/platform/audit-evidence",
  "/platform/enterprise-learning-modernisation",
  "/platform/integrations",
  "/platform/technical-overview",
  "/programs",
  "/programs/educational",
  "/programs/compliance",
  "/programs/product-enablement",
  "/programs/operational-procedures",
  "/programs/hybrid-verification",
  "/industries",
  "/industries/financial-services",
  "/industries/healthcare-life-sciences",
  "/industries/energy-resources",
  "/industries/government-defence",
  "/industries/professional-services",
  "/industries/higher-education",
  "/case-studies",
  "/case-studies/regulated-financial-services",
  "/case-studies/national-healthcare-operator",
  "/case-studies/critical-infrastructure",
  "/insights",
  "/insights/knowledge-structure-before-content",
  "/insights/what-verification-really-measures",
  "/insights/why-training-fails-audits",
  "/insights/scorm-is-a-transport-not-a-strategy",
  "/insights/knowledge-drift-and-how-to-detect-it",
  "/insights/framework-first-methodology",
  "/insights/hybrid-verification-primer",
  "/insights/ai-generated-content-and-compliance-risk",
  "/trust",
  "/trust/security",
  "/trust/compliance-posture",
  "/about",
  "/who-can-use-this",
  "/demonstration",
  "/privacy",
  "/terms",
  "/accessibility-statement",
];

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();
  return routes.map((path) => ({
    url: `${site.url}${path}`,
    lastModified: now,
    changeFrequency: path === "" ? "weekly" : "monthly",
    priority: path === "" ? 1 : path.startsWith("/platform") || path.startsWith("/industries") ? 0.8 : 0.5,
  }));
}
